### ISSUE TITLE
Add rules from Erica Sadun

### ISSUE THREAD

**Issue by jpsim** [realm/SwiftLint#202]
Lots of good stuff in here that we could turn into SwiftLint rules: http://ericasadun.com/2015/11/17/a-handful-of-swift-style-rules-swiftlang/

Notably, the following rules should be straightforward to implement:
- [x] The Rule of Conditional Binding Cascades (done in #327)
- [ ] The Rule of Pattern Matching Keywords
- [x] The Rule of `isEmpty` (wip in #206)
- [x] Prefer Swift constructors to legacy ones (done in #242)
- [x] Avoid terminal semicolons even though they compile (done in #203)

**Comment by marcelofabri** [comment]
@jpsim About "Prefer Swift constructors to legacy ones", do you see another way than keeping a list of known legacy constructors and checking for their presence?

**Comment by jpsim** [comment]
That was how I was thinking of doing it, yes!
